### ISSUE TITLE
dont-push-git-when-build-fails

### ISSUE THREAD

**Issue by distributev** [distributev/the-app#1]
![build-fails](https://cloud.githubusercontent.com/assets/19224635/16256294/7daa8630-3851-11e6-8e45-c829e5df3974.png)

**Comment by nabilzhafri** [comment]
i can build without problem. need to understand your environment more

**Comment by distributev** [comment]
Which information you need?

a reliable build works on any machine / environment.

while trying to get this working don't forget about - 
gulpfile.babel should not be changed
Client side JS and CSS files should not be hard-coded by hand in index.html but instead should be injected automatically by the gulpfile.babel/bower build

It might be a good idea to search on angular-fullstack for similar 'wiredep' questions and if you find nothing just raise a issue with them and see what they answer

**Comment by nabilzhafri** [comment]
understand. the thing is it should work, since i didn't touch anything related to build config i.e. gulpfile.babel, index.html - hence it should build without problem. You can see it via github.

please try bower install again, seems like it's related to your bower components installation.

**Comment by nabilzhafri** [comment]
basically make sure you do these steps before build/serve:

```
npm install -g bower
bower install
grunt serve
```

**Comment by distributev** [comment]
I got it working - bower install solved it
I did not run bower install first time since I knew I have all deps from previous day - it's strange since bower install outputted as it was the first time executed. Is there any "cache expiration" for bower components?

**Comment by nabilzhafri** [comment]
awesome! nope it is not. but the first time you clone from github, you should run `bower install` since we don't put the bower components in the source code.

and there was probably some problem with previously run `bower install`. Just repeat the process and make sure there's no error, and you'll be good to go :)
