### ISSUE TITLE
skin-saved-for-test-loaded-for-admin

### ISSUE THREAD

**Issue by distributev** [distributev/the-app#10]
![save-for-test-get-for-admin](https://cloud.githubusercontent.com/assets/19224635/16264128/fd3f7d1c-3877-11e6-9f35-aecf66c89c7d.png)

**Comment by nabilzhafri** [comment]
i haven't pushed the final save skin functionality, it basically not working at the moment. please wait until i notify. thanks

**Comment by distributev** [comment]
OK

**Comment by nabilzhafri** [comment]
hi there! saving theme functionality is now in master. check it out :)

**Comment by nabilzhafri** [comment]
Thanks for reporting. I missed a case where it'll happen when user never save a theme before.
It should work now :)

**Comment by distributev** [comment]
Save does not work. I select a skin "red" let's say I then logout and when I do login with the same user I see again a blue skin.
