### ISSUE TITLE
05 - list-click-select-job-behaviour

### ISSUE THREAD

**Issue by distributev** [distributev/the-app#15]
![05 - list-click-select-job-behaviour](https://cloud.githubusercontent.com/assets/19224635/16486774/1dd1e498-3ec7-11e6-833a-a405c359cf21.png)

**Comment by nabilzhafri** [comment]
as explained in chat. will add it in the next push.

**Comment by distributev** [comment]
Thanks.

**Comment by nabilzhafri** [comment]
Push to kue-jobs repo. Please take  a look and check if it aligns with your request :)

**Comment by distributev** [comment]
It looks and works very well.
