### ISSUE TITLE
15 - show-are-you-sure-modal

### ISSUE THREAD

**Issue by distributev** [distributev/the-app#17]
![15 - show-are-you-sure-modal](https://cloud.githubusercontent.com/assets/19224635/16486807/4ce17b9a-3ec7-11e6-9fe8-f59a5e27073e.png)

**Comment by nabilzhafri** [comment]
okay, will add this in the next push :)

**Comment by distributev** [comment]
Thanks.

**Comment by nabilzhafri** [comment]
Push to kue-jobs repo. Please take  a look :)
