### ISSUE TITLE
20 - how-search-works

### ISSUE THREAD

**Issue by distributev** [distributev/the-app#18]
![20 - how-search-works](https://cloud.githubusercontent.com/assets/19224635/16486811/55775b3a-3ec7-11e6-9bce-245112ad4b86.png)

**Comment by nabilzhafri** [comment]
this is limitation of the search api, and i don't think its that powerful. from what i see, it seems to search based on the job's data (but i might be wrong)
Say for example, you have `email` job type with data (you can try this with current data):

```
{
  "title": "Just a dummy email job",
  "to": "dummy@user.com",
  "template": "dummy-email"
}
```

Searching for `du` apparently doesn't return any data. but searching for `dum`, or `dumm`, or `dummy` seems to return jobs. By default, kue indexes all data (this is current implementation), but if we want to just index `title` for example, we can do so. but since job's data can vary, so it's better to index all.

If you think the searching is not that accurate/powerful, we'll have to forward this to the kue team.

Let me know if you have any question.

**Comment by distributev** [comment]
Understand. Hide the search GUI element for now. As long as we provide a good filtering mechanism (which I think we do) I'm fine without this search box.

**Comment by nabilzhafri** [comment]
ok i can do that. but do we wanna disable search in the backend as well?

**Comment by distributev** [comment]
In the GUI for sure hide it for now.

In the back-end I would say not YET. It might be useful there as a sample for future search implementation if this search will show any usefulness in the future. Unless if keeping search enabled in the back-end has significant "drop performance" implications over the KUE rutime. Does kue search eats lots of more space? Does it consume significant CPU to keep the index for search on backend? And even more importantly I remember I might have read in the past that keeping search indexes on the kue back-end enabled triggers a kue bug like leaking memory or leaking redis connections or something. I don't remember exactly the situation only that I found something in these terms. Did you find anything similar? If that it the case then for sure I would prefer disabling back-end search also.

**Comment by nabilzhafri** [comment]
Yup. I did share you link regarding memory leak in our chat. Which is why now kue disable search by default. See here: https://github.com/Automattic/kue/issues/412

Let me know your decision on this

**Comment by distributev** [comment]
Yes this is the thread I saw and I was referring.

For this case please disable search both in UI and on the back-end. Hopefully this will solve also the redislab exception 'You are now at 80% or your allowed connections' -

P.S - I need to understand more about kue and redis connections - how they work together. Having a plan support huge number of jobs with what we are building now. Because of that I don't feel very comfortable getting warnings like this (and reading about things like Automattic/kue#412) just when we are about to start. What I am saying is that kue might have some limitations / issues (or might not - we need to find out) which I need to find out in early stages - if these issues exists and are real. 

I need your help that, during your existing work with KUE, keep a constant eye on these kind of things. Let me know about anything you find strange in this area.

**Comment by nabilzhafri** [comment]
Alright I will disable them both. Will keep an eye on any issue related to memory usage / connections. Let me know if you found anything also.

**Comment by nabilzhafri** [comment]
Removed search functionality for both frontend & backend.
