### ISSUE TITLE
30 - adjust-pause-jobs-labels

### ISSUE THREAD

**Issue by distributev** [distributev/the-app#19]
![30 - adjust-pause-jobs-labels](https://cloud.githubusercontent.com/assets/19224635/16486823/644ca6ce-3ec7-11e6-9428-c810f8e1faea.png)

**Comment by nabilzhafri** [comment]
noted. will include this in next push :)

**Comment by distributev** [comment]
Thanks.

**Comment by nabilzhafri** [comment]
Push to kue-jobs repo. Please take  a look :)

**Comment by distributev** [comment]
It looks good. Can you please move 'Pause All Jobs' on top and then the separator and then the individual Pause 'email' Jobs etc. This becomes more useful when there will be many types of jobs and user will not have to scroll to the bottom to find the 'Please All Jobs' option.

**Comment by nabilzhafri** [comment]
Done :)
