### ISSUE TITLE
clean-all-sequelize-traces

### ISSUE THREAD

**Issue by distributev** [distributev/the-app#2]
![clean-all-sequelize-traces](https://cloud.githubusercontent.com/assets/19224635/16256300/8e8cc56c-3851-11e6-885d-e071ae2c4a63.png)

**Comment by nabilzhafri** [comment]
Mostly are just simple comments, i'll remove them.

**Comment by distributev** [comment]
before removing from .yo-rc.json double check if something similar makes sense for bookshelfjs

http://yeoman.io/authoring/storage.html

**Comment by nabilzhafri** [comment]
what kinda similarity? i think you're referring more to the generator?

**Comment by distributev** [comment]
do you know what .yo-rc.json is supposed to do? it's related with Yo generator indeed and it has to do with the "portability between computers" of the generated project.

See what previous sequelizejs entries were supposed to do there (they were not just comments) and see if similar things are applicable for bookshelfjs.

**Comment by nabilzhafri** [comment]
this seems to require enabling bookshelfjs auto generator as well?

**Comment by distributev** [comment]
I was thinking only to manually modify .yo-rc.json with the equivalent bookshelfjs changes if these changes make sense at all.

Actually what I need is for you to explain how .yo-rc.json works and what is supposed to do. Did you see that file before in your other projects?

**Comment by nabilzhafri** [comment]
nope.
.yo-rc is basically a configuration that is used by yo generator.

Since we didn't enable any bookshelfjs generator, we don't have to touch this file at all.

From the documentation:

> The .yo-rc.json file is a JSON file where configuration objects from multiple generators are stored. Each generator configuration is namespaced to ensure no naming conflicts occur between generators.

**Comment by distributev** [comment]
OK - remove that file from the project itself. If I will come to need later I will see at that time what its usefulnesses could be.

**Comment by nabilzhafri** [comment]
alright just removed. pushed the changes to master. please verify.
