### ISSUE TITLE
/components/jobs/kue

### ISSUE THREAD

**Issue by distributev** [distributev/the-app#22]
1. move existing /components/kue files under /components/jobs/kue
2. remove any kue from the file names (i.e. kue-jobs.controller.js should be renamed to jobs.controller.js)

The component it's actually the /jobs/ - kue it's only the API used to implement the /jobs/ component 
- later another /components/jobs/agenda implementation might come

**Comment by nabilzhafri** [comment]
done. pushed to kue-jobs. please verify :)

**Comment by distributev** [comment]
Thanks for that. 

I noticed first time but then just missed to mention when I filled that. confirmation-modal.controller.js is something generic which is reusable outside of jobs/kue. Please move confirmation-modal.controller.js out of the /components/jobs/kue/controllers under either /components/modal or /components/util whichever you find more appropriate for keeping this utility.

**Comment by nabilzhafri** [comment]
good suggestion. moved to components/confirmation-dialog
