### ISSUE TITLE
no custom css

### ISSUE THREAD

**Issue by distributev** [distributev/the-app#23]
If we use bootstrap - then we should we bootstrap.

It's possible to achieve what is required to achieve with 0 custom CSS? Of course the end result should continue to look great.

One of the aims of frameworks like bootstrap, foundation, etc. was to eliminate the need for such adhoc custom CSS. 

![no-css](https://cloud.githubusercontent.com/assets/19224635/16515334/b515700e-3f71-11e6-8806-87c82e6eb18a.png)

**Comment by nabilzhafri** [comment]
actually i don't really agree with that. bootstrap, foundation and etc, as their name suggests, gave us the foundation of our styling, and speed up the styling as well. we can always modify where we find fit. this is exactly what happen when we decide to use adminlte theme :) its basically override bootstrap styling.

also:
some doesn't seem to be supported with the shipped bootstrap.css i.e text-transform. I tried to upgrade bootstrap.css but it seems to cause broken layout/theme, so I don't wanna take a risk.
.label-inactive is to represent better color than the one comes with bootstrap.

**Comment by distributev** [comment]
OK.
