### ISSUE TITLE
capital-letter

### ISSUE THREAD

**Issue by distributev** [distributev/the-app#24]
![capital-letter](https://cloud.githubusercontent.com/assets/19224635/16515554/df0bae68-3f72-11e6-85a7-a19a4fb1c074.png)

**Comment by nabilzhafri** [comment]
you can there's a pattern there. anything from angular will start with dollar sign follow by small letter:
`$scope`, `$interval`, `$q`

when creating our own service, I can see the convention is to start with uppercase letter
`JobsManager`, `Job`, etc.

**Comment by distributev** [comment]
OK
