### ISSUE TITLE
filter-issue

### ISSUE THREAD

**Issue by distributev** [distributev/the-app#25]
![filter-issue](https://cloud.githubusercontent.com/assets/19224635/16518576/e5489b40-3f83-11e6-9040-9bcbfd326848.png)

**Comment by nabilzhafri** [comment]
looks right to me. the one you pointing out earlier is email jobs with status = complete.
When switching to email jobtype, status filter becomes inactive by default (because api doesnt support show all status when job type is selected).

Then when you switch back to Show All Types, status filter is inactive, where earlier show status filter is show all status, hence the difference.

**Comment by distributev** [comment]
Here we are mixing two things which should not be mixed. 
1. what the user would normally expect and what he gets instead
2. a possible technically API limitation

I agree that there might be a tech API limitation behind the scene based on which you had to take some decisions - however the aim is to make the underlying tech limitations leak as less as possible up to the user.

If indeed the tech limitation is there then another approach might hide it better. Before changing the filtering approach I need to understand there is no other choice.

**Comment by nabilzhafri** [comment]
Agree. By automatically changing the state to inactive due to the limitation is somewhat confusing. 

Here's my suggestion: hide show all statuses even when job type is not selected, and decide which status to be shown by default.

Let me know what you think

**Comment by distributev** [comment]
GET /job/search?q=email see what is returns 
and then use returned IDs to call GET /jobs/:from..:to/:order?

or as an alternative

try GET /jobs/:type/ - see what is returns

**Comment by nabilzhafri** [comment]
same as my other response:
search api cannot be used as a workaround here. it's more for searching jobs data.
and there's no /jobs/:type/, there's only /jobs/:state/.

**Comment by nabilzhafri** [comment]
closed. not really a bug.
similar to the other ticket: https://github.com/distributev/the-app/issues/16
