### ISSUE TITLE
small-gui-adjustments

### ISSUE THREAD

**Issue by distributev** [distributev/the-app#26]
![gui01](https://cloud.githubusercontent.com/assets/19224635/16519678/0a21e78a-3f8b-11e6-9d04-683aa0101d86.png)
![gui02](https://cloud.githubusercontent.com/assets/19224635/16519684/11dbdcce-3f8b-11e6-8311-f94a9c0525c2.png)

**Comment by nabilzhafri** [comment]
Pushed. please take a look

**Comment by distributev** [comment]
1. What is the meaning of Delayed? It's the same as 'Queued' - what is the state which a job get immediately after submission to the kue (before it starts to be processed)
2. What is the meaning of 'Inactive' jobs?
3. What is the meaning of 'Active' jobs?

Complete and Failed are obviously self-explanatory (from user's perspective)

**Comment by nabilzhafri** [comment]
1. Inactive - job is created, but never/not yet processed.
2. Active - job is currently processing, and not yet done i.e. `done()` is not yet called. 
3. Delayed - I guess this is just delay from when it's supposed to be processed. When creating a job, you can specify it to be delayed:

```
var email = queue.create('email', {
    title: 'Account renewal required'
  , to: 'tj@learnboost.com'
  , template: 'renewal-email'
}).delay(milliseconds)
  .priority('high')
  .save();
```

To sum it up:
Create job: `inactive` / `delayed` (depends on delay flag)
Process job: `active`
Job complete: `complete` / `failed` (depends if there's error or not)

I'll add some delay jobs in the seed data.

**Comment by nabilzhafri** [comment]
Added some delayed jobs. These jobs are not processed so its `delayed` status will remain.

**Comment by distributev** [comment]
Thank you for the clarification with the meaning of states and for adding the delayed jobs.
