### ISSUE TITLE
empty-screen-instead-of-login

### ISSUE THREAD

**Issue by distributev** [distributev/the-app#27]
Sometimes when I run gulp serve I get an empty screen instead of the expected login screen. Usually if I stop and start again it works fine 2nd time. What could be the cause?
![empty-screen-instead-of-login](https://cloud.githubusercontent.com/assets/19224635/16539859/d803df86-404f-11e6-986b-cf0f802c999d.png)

**Comment by nabilzhafri** [comment]
Log seems fine, no issue there. Never see that happen also.
If you know how to reproduce the problem, kindly let me know.

Next time it happened, make sure you capture the browser console as well.

**Comment by distributev** [comment]
Please mind the URL which is localhost:9000 (instead of localhost:9000/login).

Does that mean anything?

**Comment by nabilzhafri** [comment]
Sounds to me like you're not login, but somehow it doesn't redirect you automatically to login page (this should be the case). i couldn't find a way to reproduce - but if you find it again, please update me

**Comment by distributev** [comment]
many times I run gulp serve and everything works I am asked to /login
sometimes I run the same gulp serve but I get a blank screen

The behavior should be consistent and should work all the time.

**Comment by distributev** [comment]
If this it's related with #42. Probably the root cause is the same.

**Comment by nabilzhafri** [comment]
#42 is the same as this one. You can merge them.

Anyway, just pushed a fix for this one. Please verify. Thanks!

**Comment by nabilzhafri** [comment]
Added fixed for error when running `gulp serve:dist`

See commit: https://github.com/distributev/the-app/commit/e113248e5e90cc46e98eca3b4138ff3d958ae9f3

**Comment by distributev** [comment]
when doing gulp serve:dist now /login is coming but cannot authenticate - I get emptyResponse
