### ISSUE TITLE
package.json extra dependencies

### ISSUE THREAD

**Issue by distributev** [distributev/the-app#33]
It's a good practice to minimize the number of dependencies.
1. Where do you need the request.js dependency?
2. Further more bluebird.js dependency was introduced when bookshelf project was developed - At that time I tried to understand if bluebird.js it's really required and the answer was "it's a promise library and it's good to have it there"

Now I see that q.js, another promise library, dependency is also added. Please remove q.js and use the existing dependency bluebird.js to achieve the same.

![package](https://cloud.githubusercontent.com/assets/19224635/16547194/4c7d75a0-4165-11e6-8c3c-85de5d6857f4.png)

**Comment by nabilzhafri** [comment]
Sorry about this one, should've used existing bluebird. I'm just so used of using q library that I ended up using it :)

Fixed it and now it's using existing bluebird.

`request` library is needed for me to make local kue api call - it's for that "show all for job type" feature request

**Comment by distributev** [comment]
Thank you for sticking with just one single promise library.

As for request it's possible to get rid of this also? It's not only that it adds one extra dependency but it's also doing heavy local-remote. On /server/ instead of doing request json API calls just do direct KUE api calls (json API is only a wrapper to a their usual API) - this will get rid of request dep and it's also how it should be done locally on /server

**Comment by nabilzhafri** [comment]
Pushed fix - removed dependency to request module and use kue api instead.

See commit here:
https://github.com/distributev/the-app/commit/c932c7fb1f8efcb14b2163ab4c80951dc1fccda0
