### ISSUE TITLE
place the sqllite3 database file here.txt

### ISSUE THREAD

**Issue by distributev** [distributev/the-app#37]
theapp-template/TheApp/_internal/data/place the sqllite3 database file here.txt

This one remained like that?

Where is the sqllite3 db file currently stored?

**Comment by luismanuel001** [comment]
The dist.sqlite db file gets created on that folder once you run the application, but it is ignored from git to not pollute the repo.

The other non-production db's dev.sqlite and test.sqlite are currently just stored at the project root when the app runs on dev and test environments. but they also get ignored by git to not pollute the repo.

Should I chaneg the default path of these so they get stored on the same directory as dist.sqlite?

**Comment by distributev** [comment]
Not required to move existing dev.sqlite and test.sqlite

Just remove this place the sqllite3 database file here.txt

Does git allows empty folders?

**Comment by luismanuel001** [comment]
yes it does.

ok I'll go ahead and remove this file.
