### ISSUE TITLE
port 8080 instead of default node/express port

### ISSUE THREAD

**Issue by distributev** [distributev/the-app#43]
How got the port changed?

I think default node/express port is 9090 or something. Please put it back

![blank-screen](https://cloud.githubusercontent.com/assets/19224635/16630354/54f42ba0-43ba-11e6-81ec-f46c187b67e6.png)

**Comment by luismanuel001** [comment]
This has not been changed.  This is the default behavior, the app runs on port 9000 on development and on port 8080 on production.  you can check the config/environment files.
