### ISSUE TITLE
How can the port on which the application runs can be changed?

### ISSUE THREAD

**Issue by distributev** [distributev/the-app#44]
Please put back default express/node.js port.

If it will be required to change the port on which the application runs how this can be done?

**Comment by luismanuel001** [comment]
You can change it in the config/environment/production.js file here: https://github.com/distributev/the-app/blob/master/server/config/environment/production.js#L45

**Comment by distributev** [comment]
I see it can be changed through command line when app is started.
Can you show me an example with the command to start the app with a different port?
