### ISSUE TITLE
merge-admin-lte functionality

### ISSUE THREAD

**Issue by distributev** [distributev/the-app#5]
from https://github.com/distributev/ng-admin-lte repository

including Customers and Transactions

I remember I said to leave Customers / Transactions out but I need menu.js functionality from that repository and I forgot Customers and Transactions are supposed to test that menu.js works fine.

The final result should contain only our own functionality and not any "dummy" feature (thing) from angular-fullstack

**Comment by nabilzhafri** [comment]
i will do this. will update here once done

**Comment by nabilzhafri** [comment]
pushed to master. please verify
