### ISSUE TITLE
hexo-admin

### ISSUE THREAD

**Issue by luismanuel001** [distributev/the-app#55]
I'm having an issue trying to setup the hexo-admin plugin to work with our setup.

Basically since we are running "hexo generate" and then serving the files generated statically, hexo admin wont work as explained here: https://github.com/jaredly/hexo-admin/issues/37.

Also while looking up a solution for this issue, I realized that hexo-admin doesn't let you create/edit/remove pages yet: https://github.com/jaredly/hexo-admin/issues/2, and I thought this was the main point of having hexo-admin on this project, so the users can manage content (pages) from a UI instead of relying on the console for all interaction.

Also looked at another admin UI hexo-hey (https://github.com/nihgwu/hexo-hey) but they don't have support to edit/create pages either (https://github.com/nihgwu/hexo-hey/issues/10), only posts, just like hexo-admin

**Comment by distributev** [comment]
This should be "good enough" - 

page editing is working! - https://github.com/jaredly/hexo-admin/commit/2b5f8529585fc2a6e9afe451f36af6e355a88e66

**Comment by luismanuel001** [comment]
#72
