### ISSUE TITLE
client/index.html

### ISSUE THREAD

**Issue by distributev** [distributev/the-app#59]
Why client/index.html was renamed to client/app-index.html? We put hexo in its own separate 
/frontend folder ==> we will not have to touch too much the /client folder

Why was <script src="components/contact-details/contact-details.directive.js"></script> included in client/index.html? (it is not used there)

Only purpose for contact-details.directive.js is to test angularjs support on /frontend

**Comment by luismanuel001** [comment]
The file needed to be renamed to something different than index.html because the express router was using it as the main entry point because of the order of precedence of the files/routes.

**Comment by distributev** [comment]
Why was contact-details.directive.js included in client/index.html? (it is not used there)

Only purpose for contact-details.directive.js is to test angularjs support on /frontend

**Comment by luismanuel001** [comment]
Because I thought you told me that you wanted to test the use of directives across the 2 UI's (/theapp and the /frontend), and all .js files on the /client folder get automatically added to app-index.html by the existing gulp tasks created from angular-fullstack.

**Comment by distributev** [comment]
OK - this is fine if gulp added automatically - I don't take the trouble to change this. 
contact-details.directive.js was built mainly to test angularjs support on frontend.
