### ISSUE TITLE
runtime-error

### ISSUE THREAD

**Issue by distributev** [distributev/the-app#6]
gulpfile.babel should not be changed
Client side JS and CSS files should not be hard-coded by hand in index.html but instead should be injected automatically by the gulpfile.babel/bower build

If you find it's an issue with angular-fullstack look on their issue tracker if somebody else raised the same and what was the solution.
If you find it's an issue with angular-fullstack but you don't find any issue raised yet for that - please raise yourself the issue and past the link to the issue here so I can follow up with the proposed solutions.
![runtime-error](https://cloud.githubusercontent.com/assets/19224635/16261383/9e90739a-386b-11e6-8449-f0e7259366d5.png)

**Comment by nabilzhafri** [comment]
i remember you mentioned this earlier that it was an existing issue?

**Comment by nabilzhafri** [comment]
See here:
https://github.com/angular-fullstack/generator-angular-fullstack/issues/1582
https://github.com/angular-fullstack/generator-angular-fullstack/issues/670
http://stackoverflow.com/questions/35712368/csrf-token-missing-ionic-angularjs-fullstack
http://stackoverflow.com/questions/35145063/403-when-posting-in-postman-using-yeomans-angular-fullstack

It's basically needed by lusca (https://www.npmjs.com/package/lusca)

We can just disable it.

**Comment by distributev** [comment]
Is that CSRF something useful during the login? Why angular-fullstack uses lusca does it provides any "added value" - if so - it's a defect in lusca or it's a misconfiguration somewhere?

**Comment by nabilzhafri** [comment]
not really familiar with this one, but seems like it's some sort of protection for expressjs middleware. i guess it requires extra configuration

> Cross-Site Request Forgery (CSRF) is an attack that forces an end user to execute unwanted actions on a web application in which they're currently authenticated. CSRF attacks specifically target state-changing requests, not theft of data, since the attacker has no way to see the response to the forged request.May 22, 2016

i believe your application will be portable and not on the web right, then you don't really need it.

**Comment by distributev** [comment]
The application works in dual mode - portable and configurable for web.

Please spend 10 minutes (probably on lusca github issues) and see if it's a defect with them or angular-fullstack issue or it's just an additional configuration which needs to be done on our side.

Let me know what you will find in these 10 minutes about CSRF / lusca error and then I'll see what needs to be done.

For me coming from different background (java) It's very strange to see a high profile nodejs project like angular-fullstack starts to give runtime stacktrace after 1 or 2 clicks in the GUI - because of that I want to double check it's not actually on our side something which we need to enable.

**Comment by nabilzhafri** [comment]
you can try the link I shared before. Seems like this guy has a solution: https://github.com/angular-fullstack/generator-angular-fullstack/issues/670

**Comment by distributev** [comment]
OK - try to apply the same and see if it works.

**Comment by nabilzhafri** [comment]
Another post: Seems to me you'll have to handle this manually. You'll have to add x-csrf-token into the header:
https://github.com/krakenjs/lusca/issues/73

**Comment by nabilzhafri** [comment]
Sorry, I think it's not part of the original project requirement to take care of this kinda issue. Sorry its not that I don't wanna help, but I'm also working on other projects at the same time. Since I'm not familiar with this functionality, I'm afraid it'll take too much of my time to figure it out. But anything related issue to my tasks, I'll try to fix them as soon as possible.

Hope you understand. Thanks

**Comment by distributev** [comment]
either this project - either the admin-lte project - one of them is incomplete. because in both it was part of the requirements 

The delivered code should be free of any warnings and/or errors at build and/or runtime.

I did release the payment for admin-lte at that time even if the above was not true. Now I understand I should have not.

P.S - please understand this is not to "keep" your from working fast and closing projects and moving forward. Moving forward quick it's actually what I am looking after also.

In the same time I will not compromise on quality - If I get errors / warnings after 2 clicks in the GUI when I do login how I will keep errors/warnings adding up when I will start to add lots of serious functionality. I need to move fast pace and have high quality also. Is that possible?

**Comment by distributev** [comment]
For this issue please raise an issue to angular-fullstack- tell them it was already raised in the past by other people which came with "adhoc" solutions to manually fix but you really feel this should be put directly into angular-fullstack since it's related with their provided login boilerplate.

Once you raise the issue with them paste the URL here.

**Comment by nabilzhafri** [comment]
Okay, maybe I misunderstood. My understanding before is that my codes should be free of warning / errors, and shouldn't touch any existing functionality. You did mention previously that I shouldn't touch any existing functionality. Please advise.

**Comment by distributev** [comment]
this is not functionality but a defect. An "inherited" one indeed. Nevertheless this inherited defect stops you now from delivering current project as per "The delivered code should be free of any warnings and/or errors at build and/or runtime." 

The same was true for admin-lte project but I closed my eyes and released the project. This CSRF we are moving from one project to another. 

Are you fine if you raise CSRF issue with fullstack and explain you get this error on their "out of the box" login boiler plate? 

And tell them upfront few people found "adhoc" solutions to manually fix the code but you believe the fix should be handled directly into the fullstack project otherwise a stacktrace is raised on their provided login boilerplate.

**Comment by nabilzhafri** [comment]
Understand. I will try fix it and file issue to them. Thanks

In the meantime, please tell me how to reproduce the issue since I cant see the error.

**Comment by distributev** [comment]
If you raise to fullstack it will be good enough for me for this project. Don't fix anything yet. Let them answer and suggest best approach.

For following (projects) we will apply what they would suggest we need to do (or we will incorporate their fix if they will apply any fix meenwhile)

**Comment by distributev** [comment]
Just attach my screenshot to the issue you raise with them.

**Comment by distributev** [comment]
Once you raise the issue with them paste the issue's URL here and you can close this case.

**Comment by nabilzhafri** [comment]
Noted. But can you please share how to reproduce, so I can mention this when I file an issue with them

**Comment by distributev** [comment]
I just do login and I see that error message on my DOS console. Nothing special. I use Opera browser for testing if that makes any difference.

**Comment by nabilzhafri** [comment]
This seems very intermittent issue. Need to see how to produce them always.

**Comment by nabilzhafri** [comment]
Hi, I've pushed the fix to master. Check it out!
