### ISSUE TITLE
Move all the new hexo: tasks under /* custom tasks */ area

### ISSUE THREAD

**Issue by distributev** [distributev/the-app#61]

**Comment by luismanuel001** [comment]
These are all already under the /\* custom tasks */ area.

The only changes I made outside the  /\* custom tasks */ area are only necessary ones, like adding a hexo: task to a runSequence(), and those cannot go in the custom tasks area.

**Comment by distributev** [comment]
OK - sorry -

I though they might be already under /\* custom tasks */ but sometimes on github viewing file diffs can be misleading. So I raised this to be on safe side.
