### ISSUE TITLE
same deps in 2 different package.json files

### ISSUE THREAD

**Issue by distributev** [distributev/the-app#62]
Why "hexo": "^3.2.2" and "hexo-admin": "^2.1.0" dependencies are added in 2 different package.json files? (main's project package.json and hexo's package.json)

**Comment by luismanuel001** [comment]
I tried extracting all dependencies to the main project's package.json, but then Hexo failed to process files. Hexo seems to require that the /node_modules folder to be at the hexo root for it to work properly.
