### ISSUE TITLE
head.ejs

### ISSUE THREAD

**Issue by distributev** [distributev/the-app#63]
What is this open_graph({ **_description: "_** " added there? change supposed to do in

/TheApp/_internal/app/frontend-hexo/frontend/themes/corporate/layout/_partial/head.ejs

**Comment by luismanuel001** [comment]
With the default settings, open_graph() was just automatically adding a description meta tag to the header with the values of the pages content, which in the case for the /document page, it would have add a description of [[doc_html]](which is a variable I use to switch the dynamic document content) so by setting it to { description: " " } it removes the description meta tags.  When no description meta tag is present, crawlers infer it from the final content, which is a better practice than having an empty/false description according to SEO best practices.
