### ISSUE TITLE
warnings-on-build

### ISSUE THREAD

**Issue by distributev** [distributev/the-app#7]
The git pushed code should be free of any warnings and/or errors at build and/or runtime.

gulpfile.babel should not be changed
Client side JS and CSS files should not be hard-coded by hand in index.html but instead should be injected automatically by the gulpfile.babel/bower build

I keep repeat pasting this here since previous freelancers tried to "fix" similar issues by removing the javascript linting rules from the build. Once I will see it's safe and you don't mess with gulpfile.babel and you don't hardcode deps in index.html then I will not repeat (copy-paste) the same pre-requisite rules.

again check if it's an issue with angular-fullstack and if so search their repository for solutions and if there is none - raise yourself the issue. This is the approach we need to take.
![warnings-on-build](https://cloud.githubusercontent.com/assets/19224635/16261603/7d5a8502-386c-11e6-937c-a51ec02b6cca.png)

**Comment by nabilzhafri** [comment]
ah sorry my bad. it was fix in the other repo. i forgot to update jshint config. AngularJS best practice doesn't match the default jshint config. let me update it

**Comment by nabilzhafri** [comment]
and note that by default, gulpfile.babel somehow exclude bootstrap files from being included. Without changing the file, there's no way i can include them automatically. Please advise

**Comment by distributev** [comment]
for "gulpfile.babel somehow exclude bootstrap files from being included" raise the issue on fullstack repository. Ask them "Please advice" to see what they say.

Please - don't update jshint config - do the same raise the issue on fullstack repository and ask their advice what is to be done to get their project build without warnings and without disabling js linting.

**Comment by nabilzhafri** [comment]
gulpfile.babel exclude the bootstrap because they explicitly include it in the excluded files. Thats why I have to update gulpfile.babel to remove bootstrap from excluded file.

JShint is just a configuration. It's something that can always be modify, depending on your project requirements and code styling. The current jshint config by default shows warning when I follow angularjs best practice. This is not something we wanna raise issue to them. They provide us with a boilerplate/template, and it's up to use to follow or update the jshint config to follow our own code styling.
There are 2 ways to fix without disabling js linting:
1) Update my angular codes styling to make sure it doesn't cause warning and follow current jshint config
2) Flag my angular codes to ignore this particular rule of jshint that cause warning
Please advise which you prefer.

**Comment by distributev** [comment]
I searched gulpfile.babel.js and did not find where they exclude the bootstrap. Please show me where bootstrap is excluded.

Why they would exclude bootstrap when bootstrap is a library which is at the foundation of angular-fullstack?

---

"The current jshint config by default shows warning when I follow angularjs best practice."

JSHint default config is something provided by angular-fullstack project? If so then it should align with "angularjs best practices" 

==> 

it makes sense to raise the issue with  angular-fullstack to align themselves with best angularjs practices (otherwise they will align with which best practices .Net maybe?)

**Comment by nabilzhafri** [comment]
That isn't something I can answer. See below:
![image](https://cloud.githubusercontent.com/assets/6986883/16264422/22ebba10-38ac-11e6-8ace-f97bc4510a79.png)

---

I will file issue to them, but in the meantime, you should tell me what I should do next? Fix jshint config file, or fix my code. Thanks

**Comment by distributev** [comment]
For both bootstrap and jshint raise issues with angular-fullstack
1. what is the reason they exclude /bootstrap.js/ considering bootstrap is a foundational library for fullstack
2. Suggest fullstack to update their own jshint to accommodate "best angularjs practices" (since fullstack is a project based on angularjs)

**Comment by nabilzhafri** [comment]
Understand, I will file issue to them regarding best angularjs practice. But for now, please advise how should I proceed with the code to remove the warnings. Thanks

**Comment by distributev** [comment]
Fill both issues with them and for both paste the issue's URLs here.

Then for this project only 
- index.html hard-coding can remain there.
- JSHint warnings can remain there

For following projects we will see what they answer/suggest for both cases and apply on our code their fixes/suggestions.
For now just raise the issues and put here links.

**Comment by nabilzhafri** [comment]
Noted. Sounds good.

I also not sure why don't they follow angular best practices when their project itself is about angularjs.
Well, I guess they're not following the best practices :) I can see the generated code also not following best practices. Will mention this as well.

I'll send you the links in a bit.

**Comment by nabilzhafri** [comment]
Hi, I've filed the ticket. See here:
Bootstrap:
[https://github.com/angular-fullstack/generator-angular-fullstack/issues/2011](https://github.com/angular-fullstack/generator-angular-fullstack/issues/2011)

JSHint:
[https://github.com/angular-fullstack/generator-angular-fullstack/issues/2010](https://github.com/angular-fullstack/generator-angular-fullstack/issues/2010)

**Comment by nabilzhafri** [comment]
Another one on gulp build, which is the hardcoded index.html at the moment:
https://github.com/angular-fullstack/generator-angular-fullstack/issues/2012

**Comment by nabilzhafri** [comment]
Apparently bootstrap.js is only included in the exclude block when UI Bootstrap is chosen, that's why.
I'll update my code to use UI bootstrap element, and revert the gulpfile back

**Comment by distributev** [comment]
You are doing good work. 

OK - update your code to use included UI bootstrap.

OK to change JSHint as per John Pappa's styles (keep in mind these are John Pappa's styles only and not angularjs official styles)

As for the hardcodings in index.html let's wait for fullstack to answer. It's seems strange that half of dependencies to be handled by bower and other half manually hard-coded. The whole point of using bower is missed when doing that. We could very well hard-code everything.

**Comment by distributev** [comment]
Do not disable all JS linting - just do the JSHint required change to enable that specific 'late function declaration'

**Comment by nabilzhafri** [comment]
1) Updated my code to use UI bootstrap. For now, it's only being used for user dropdown - menu 
2) Updated JSHint to allow late definition i.e. `"latedef": "nofunc"`
3) Hard coded index.html - they just replied that it might be an issue. lets wait for more response

**Comment by nabilzhafri** [comment]
Good news! I've finally figured out how to fix the auto inject when building based on their response. Now no more hard coded inside index.html (except `<admin-lte></admin-lte>`, of course).

One was their existing issue, which I've included in the fix as well.

I've pushed the changes to master. Please take a look.

**Comment by nabilzhafri** [comment]
Please verify this, and close the ticket accordingly.
