### ISSUE TITLE
small differences from frontend-fullstack-dynamic-page.png

### ISSUE THREAD

**Issue by distributev** [distributev/the-app#70]
If you check frontend-fullstack-dynamic-page.png from requirements and the actual GUI you will see some small differences (remove the twitter feed and add the Our Clients area above the footer) -

http://hexotest.computerlab.io

Try to come close to frontend-fullstack-dynamic-page.png

**Comment by luismanuel001** [comment]
The Our Clients area is not part of the theme layout on the demo, it only shows up on the index.html, do you want me to copy this and add it also to the index/home of our hexo site?

**Comment by distributev** [comment]
No. Leave it out. 

Make the rest of the things look the same like frontend-fullstack-dynamic-page.png
