### ISSUE TITLE
existing-functionality-should-continue-to-work

### ISSUE THREAD

**Issue by distributev** [distributev/the-app#75]
![existing-functionality-should-continue-to-work](https://cloud.githubusercontent.com/assets/19224635/17137840/9ebd611a-533d-11e6-8da4-1fcf72cb6e5b.png)

**Comment by luismanuel001** [comment]
Yes this was tested and it is working fine.  The way ui-router works, all jobs.\* states will inherit the jobs state URL as a prefix, so jobs.all becomes /theapp/jobs/, jobs.startStop becomes /theapp/startstop etc.
