### ISSUE TITLE
bin/hexo commands

### ISSUE THREAD

**Issue by distributev** [distributev/the-app#77]
1. hexo.bat which commands are available / useful to user?
2. how do I test hexo-admin.bat?

**Comment by luismanuel001** [comment]
1. All commands in https://hexo.io/docs/commands.html should work just fine by going into the /bin directory on the command prompt and running `hexo <command>`. For example you can run any of the following commands:

```
hexo clean
hexo generate
hexo new page <page-title>
hexo list page
```
1. You can go to the bin directory and run `hexo-admin` fromt he command prompt or just double click the hexo-admin.bat file on the windows explorer.
