### ISSUE TITLE
blured about us on documents

### ISSUE THREAD

**Issue by distributev** [distributev/the-app#81]
![blured-about-us](https://cloud.githubusercontent.com/assets/19224635/17151846/78f5f7c0-5375-11e6-89ad-f2f8ce8da172.png)

**Comment by luismanuel001** [comment]
This is because the sample html used for the invoices (the one you provided on the specifications) has some pretty generic css that targets .body, so I think they are messing up with the theme's own css.

**Comment by distributev** [comment]
documents should be rendered self contained (should not interfere with external html page / template) - please isolate / render documents in their own <iframe>{{"[[doc_html]]"}}</iframe>

I tried myself the above on hexo-admin but could not get any <iframe> ==> could not see any <iframe> rendered. Do you know why?
